package org.amrvimag.bocateria.view;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Adrian MRV. aka AMRV || Ansuz
 */
public class ProductInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductInfoPanel
     */
    public ProductInfoPanel() {
        initComponents();
        icon.setText("");
    }

    public void setImage(Image image) {
        icon.setIcon(new ImageIcon(image));
    }
    
    public void setImage(Icon icon) {
        this.icon.setIcon(icon);
    }
    
    public void setPrimaryText(String text) {
        primaryText.setText(text);
    }
    
    public void setSecondaryText(String text) {
        secondaryText.setText(text);
    }
    
    public void setDetailText(String text) {
        detailText.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        primaryText = new javax.swing.JLabel();
        secondaryText = new javax.swing.JLabel();
        detailText = new javax.swing.JLabel();

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setText("jLabel1");

        primaryText.setText("jLabel2");

        secondaryText.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledText"));
        secondaryText.setText("jLabel2");

        detailText.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primaryText)
                    .addComponent(secondaryText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(detailText)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(primaryText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(secondaryText)
                .addContainerGap())
            .addComponent(detailText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailText;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel primaryText;
    private javax.swing.JLabel secondaryText;
    // End of variables declaration//GEN-END:variables
}
